source "https://rubygems.org"

gem "rails", git: "git://github.com/rails/rails.git", tag: "v5.1.0.beta1"
gem "pg"
gem "sass-rails"
gem "autoprefixer-rails"
gem "uglifier"
gem "therubyracer", platforms: :ruby
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder"
gem "redis"
gem "sprockets"
gem "bootstrap-datepicker-rails"
gem "twitter-typeahead-rails"
gem "font-awesome-rails"
gem "ckeditor"
source "https://rails-assets.org" do
  gem "rails-assets-tether"
end
gem "react-rails"
gem "hamlit"
gem "puma"
gem "acts_as_tree"
gem "elasticsearch-rails"
gem "elasticsearch-model"
gem "sidekiq"
gem "readthis"
gem "hiredis"
gem "simple_form"
gem "virtus"
gem "shrine"
gem "fastimage"
gem "aws-sdk"
gem "roda"
gem "jquery-fileupload-rails"
gem "coverband"
gem "byebug"
gem "factory_girl_rails"
gem "rspec-rails"
gem "rails-controller-testing"
gem "jasmine-rails"
gem "spring-commands-rspec"
gem "rubocop", require: false
gem "webmock", require: false
gem "rubycritic", require: false
gem "faker"
gem "spring"
gem "spring-watcher-listen"
gem "spring-commands-cucumber", git: "https://github.com/jonleighton/spring-commands-cucumber.git", branch: "master"
gem "web-console"
gem "listen"
gem "capybara"
gem "poltergeist"
gem "capybara-screenshot"
gem "formulaic"
gem "cucumber-rails", require: false
gem "headless"
gem "selenium-webdriver"
gem "site_prism", git: "https://github.com/natritmeyer/site_prism.git", branch: "master"
gem "database_cleaner"
gem "shoulda-matchers"
gem "simplecov", require: false
gem "simplecov-json", require: false
gem "ci_reporter_rspec"
gem "rspec-sidekiq"
gem "faraday"
gem "rails_12factor"
