source "https://rubygems.org"

gem "rails", "~> 5.1.4"
gem "webpacker"
gem "bootsnap", require: false
gem "pg"
gem "sass-rails"
gem "autoprefixer-rails"
gem "uglifier"
gem "therubyracer", platforms: :ruby
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder"
gem "redis"
gem "sprockets"
gem "font-awesome-rails"
gem "ckeditor"
gem "react-rails"
gem "hamlit"
gem "puma"
gem "acts_as_tree"
gem "elasticsearch-rails"
gem "elasticsearch-model"
gem "sidekiq"
gem "readthis"
gem "hiredis"
gem "simple_form"
gem "virtus"
gem "shrine"
gem "fastimage"
gem "aws-sdk-s3"
gem "roda"
gem "coverband"
gem "byebug"
gem "factory_bot_rails"
gem "rspec-rails"
gem "rails-controller-testing"
gem "jasmine-rails"
gem "spring-commands-rspec"
gem "rubocop", require: false
gem "rubycritic", require: false
gem "faker"
gem "spring"
gem "spring-watcher-listen"
gem "web-console"
gem "listen"
gem "capybara"
gem "capybara-screenshot"
gem "cucumber", "2.4.0"
gem "cucumber-rails", require: false
gem "headless"
gem "selenium-webdriver", "3.4.0"
gem "site_prism", git: "https://github.com/natritmeyer/site_prism.git", branch: "master"
gem "database_cleaner"
gem "shoulda-matchers"
gem "simplecov", require: false
gem "simplecov-json", require: false
gem "ci_reporter_rspec"
gem "faraday"
